### ISSUE TITLE
Create event-bus integration tests

### ISSUE THREAD

**Issue by Cooryd** [libero/continuum-adaptor#25]
Following #24 we should be able to subscribe to an event bus then destroy its instance to prevent hanging code in jest tests. We should write integration tests for the following:

- Check an event is emitted for authorisation on successfully hitting `/authenticate`
- Check no event is emitted for rejected `/authenticate` requests

**Comment by erezmus** [comment]
should we add blocked label? @Cooryd

**Comment by will-byrne** [comment]
moved back due to how time consuming it was becoming. Existing branch is `add_event_bus_integration_test`
tests pass in local ci using docker but fail on travis.

**Comment by norisalsaadie** [comment]
Awaiting PR https://github.com/libero/event-bus/pull/20

**Comment by erezmus** [comment]
closed via #47
