### ISSUE TITLE
Change authenticate handler to only return user id in token

### ISSUE THREAD

**Issue by erezmus** [libero/continuum-adaptor#33]
See #32 

Currently the authentication handler performs the following steps:

1. Verifies the journal token
2. Retrieves the profile from the continuum api (if no profile, returns an error)
3. Bundles identity, role (hard coded), and potentially email in the token.

Since the profile is assumed to exist (its created by continuum), it should:
1. retrieve the user with the profile id or create a new user entry (along with identity) as is currently done in xpub. If an invalid profile is given, the verification of the journal token should fail and no user should be created.
2. Return the new token with the user id only as the `sub` field.

**Comment by norisalsaadie** [comment]
Just some notes to my future self

Test cases to consider:
1. Test that an empty profile doesn't throw
2. Test that a profile is created (if empty) 
3. Test that a profile is not created (if not empty)
4. Test the shape of the payload/token matches newly expected format

Things to explore:
1. How does xpub interact with the profile service?
