### ISSUE TITLE
Out dated documention

### ISSUE THREAD

**Issue by norisalsaadie** [libero/continuum-adaptor#37]
The readme mentions the use of an .env file, but seems to be using a json file for config. 

> cp .env.example .env

Is anything any other information out dated or incomplete?

**Comment by giorgiosironi** [comment]
The `.env` file would be used by `docker-compose` to interpolate variables into `docker-compose*.yml` files, but all the variables there have defaults so it's probably not necessary anymore unless someone wants to override them.
